# Generated by Django 4.1.7 on 2023-03-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='first',
            options={'verbose_name_plural': 'Crawl Data'},
        ),
    ]
