# Generated by Django 4.1.7 on 2023-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawl', '0003_alter_first_data_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='data_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
